#+TITLE: 关于用TB进行程序化交易需要注意的点
#+AUTHOR: 胡琛

1. 888 是连续主力合约的简单拼凑，有大规模跳空，一般品种每三个月将跳空排除掉才能用普通
    策略去回测，一般地话只能用日内平仓策略去做回测。

2. 000 做隔日策略的话，必须用000去回测，回测结果有好有坏，实盘一般比回测差的概率会大一些，但
    一般而言，会比回测打个八到九折。

3. 当策略是非频繁开仓策略的时候，手续费设置不需要调的很高，一般而言，初始回测可以改为 1%%手续费，
   1跳滑点，如果没有亏损，将滑点改为2跳，如果还不亏损，对于小时线之上的策略，基本上来讲，实盘是
   不会亏损了，滑点1个点一般就会比手续费高很多。

4. 关于回测区间的设置，最好采用11年，12年之后的数据一直到最近的，譬如17年数据，原因有两点，
   首先是11年，12年之前期货品种属性和现在相比变化很大，譬如11年之前铜很好做，但是11年之后
   铜就很难做了，另外就是后面品种多了以后，品种的对冲效应才体现出来。

5. 调整完一个公式后，如果要重新看公式回测效果，最好先把图表中公式删除，然后重新加载
 
6. 交易手数少是好事，在同样情况下，交易越少越好，因为交易越少出现大规模滑点累积也越小，
   当然，也需要和收益做平均来看。
 
7. 做一个权衡，回撤幅度需要远远小于利润减小的幅度，大多数月份能够盈利是最重要的，一
    般而言，sharp ratio做到1.5，每个季度是盈利的，如果做到2.0的话，那么每个月都会有
   盈利。
 
8. 最后的sharp ratio肯定要看的是多品种多周期组合的结果

9. 多品种，需要注意把开仓手数进行修改，

   #+BEGIN_EXAMPLE
     TotalEquity = 1000000+ Abs(CurrentContracts()*Close*ContractUnit()*BigPointValue()*MarginRatio());
     UseMargin = Close*ContractUnit*BigPointValue*MarginRatio;
     EntryLots = IntPart(TotalEquity*0.05/UseMargin);
   #+END_EXAMPLE
  
     平仓则都用默认值来进行平仓。

     EntryLots代表资金按照1000，000本金，加上现在整个账户的净值，折算成可以开多少合约，取整得到的一个合约数，这样应用
     到多品种上，每个品种都是投入了1000，000本金再加上相应的净值后折算合约来折腾的，这样统一起跑线，这样合约随着时间变化，
     它的保证金也在变化。

10. 为何平仓要平成 0 而不是EntryLots，是因为EntryLots是一个时间序列，随着时间改变，价格会变化，譬如开仓的时候， EntryLots
    可能是10个，结果平仓的时候， EntryLots就变成了9，会造成没有把仓位全平掉。

11. 建议将十几个到二十多个活跃品种进行回测，然后看效果，将负收益的品种去除，如果这个策略在十几个品种上都能用，一两个周期都
    能用，短期上来讲，该策略已经可以用了，就是赚多赚少，风险大小的问题了。

12. 多个策略看的是不同策略是否有对冲效应，譬如某个策略在别的策略亏钱的时候能够不亏甚至能够赚钱，那就可以在不同市场行情下
    使用不同的策略进行对冲。

13. 指标的自由度，当指标用到的变量越多的情况，过拟合的情况会比较常见，类似双均线或者比较前期高点和低点的策略问题不会太大，
    用普通技术指标发起开平仓信号时候，一定要注意它的适配度高不高，适配度不高的指标一定不能用。

14. 趋势跟踪有个很重要的指标，平均持仓周期。捕捉不同级别行情的趋势时，平均持仓周期都是在4，10或者20个周期上去看，交易
    次数越少越好，当然这个并没有一个定论。

15. 有些模型超过一半以上天数都有交易的话，那一般会有问题，这种模型，一般软件去实盘跑，会有问题，如果盈亏比很高，譬如大于2
    的情况下，胜率大于3成的情况下，那一般不会有太大问题，盈亏比低于1.5的情况下， 跑起来基本很难赚钱。

16. 螺纹钢13年整年都是震荡类行情，如果趋势类策略能够把13年过滤掉，那至少说明策略是有效的

