#+TITLE: PSY 结合 KDJ 策略
#+AUTHOR: 胡琛

* 缘由 

  =PSY= 的意义是过去一段时间内阳线的统计，如果大于某个阈值，认为市场情绪转好；反之，则差。
  一般的参数选择是统计过去 12 根 Bar 柱中阳线数目，经验上有：

  - =PSY= 值 25-75 区间是心理预期正常理性变动范围。

  - =PSY= 值 75 以上属超买区, 市势回档的机会增加。

  - =PSY= 值 25 以下属超卖区, 市势反弹的机会增加。

  - =PSY= 的 M 形走势是超买区常见的见顶形态, W 形走势是超卖区常见的见底形态。

  - =PSY= 值 90 以上或 10 以下, 逆反心理要起明显作用, 市势见顶或见底的技术可信度极高。

* 趋势类策略

  如果单纯用 =PSY= 中线 50 作为开平仓条件，一方面策略会频繁开平仓，手续费吞噬利润；另一方面，
  行情如果是震荡行情，会导致趋势没有抓到但是亏损却不断累积。

** 想法 1
  
   效仿布林通道的思想，布林通道初始思想是认为价格如果偏离价格太远，譬如两倍 sigma 的时候，价格会
   往中线回归，这是逆趋势的策略思路，但是实际操作并不会挣钱，而如果做趋势策略的话，即认为
   *价格突破布林上轨，看多；价格突破布林下轨，看空* ；对于 =PSY= 认为突破 75 的时候，看多，
   下破 25 的时候，看空，止损策略用三级止损。

   [[file:psy_trend_v1.xml]]

*** 说明
    
    查看具体的 K 线图，不少行情都是对应正好 7 根阳线或者 7 根阴线，对应的 =PSY= 值是 75 和 25，
    为了避免忽略这些行情，Long 和 Short 对应的条件设置为 'PSY >= 75" 和 "PSY <= 25".

** 想法 1 止损的改进

   1. 吊灯止损
       实际具体看回测盈利曲线，看到回撤还是太大，是不是可以换一种止损方式，这里采用吊灯止损作为尝试。
   
      [[http://a-wang109.blog.163.com/blog/static/7754201720122137386284/][吊灯止损 1]]
      [[http://blog.sina.com.cn/s/blog_7542a31c0101avpv.html][吊灯止损 2]]

      效果不佳，甚至变得更差

   2. 阶梯止损
      开多的时候，每上升一定点位，相应地将止损位往上提，有点类似跟踪止损，跟踪止损相当于阶梯为1的
      阶梯止损。

      [[https://www.ricequant.com/community/topic/1423/%25E6%25AD%25A2%25E6%258D%259F-%25E9%2598%25B6%25E6%25A2%25AF%25E6%25AD%25A2%25E6%258D%259F-%25E4%25B8%2580%25E4%25B8%25AA%25E5%258A%25A8%25E6%2580%2581%25E7%259A%2584%25E6%25AD%25A2%25E6%258D%259F%25E6%2596%25B9%25E6%25A1%2588][阶梯止损1]]
      [[http://toutiao.manqian.cn/wz_1bK4H5bihiv.html][阶梯止损2]]

      效果也一般，还是不如三级止损。
** 想法2
   单纯的 =PSY= 策略可能面对的问题，从K线图上看主要分成两个方面：
   1. 有的趋势已经开始了，但是到第12根K线的时候，接近结束，于是利用 =PSY= 策略来做，会抓不住
      这样的趋势，这样的趋势没有办法，除非切换思路。
   2. 还有的情况，可能在震荡市中，12根K线中阳线居多，但是具体看K线形态与分布，并不是在趋势中，
      这个时候，简单的 =PSY= 可能无法分辨这样的行情，如果加入另外一个快速指标对趋势做双重确认，
      效果是否会好点。
   3. 一种方案，加入震荡指标，这里采用 =KDJ= 指标，利用J的快速变化，并采用 J值大于80和小于20
      作为行情的确认。
   4. 回测效果还不错，至少相比单纯的 =PSY= 好了不少，但是盈亏比还是低于1.5，或许，可以考虑加入其他
      过滤条件。
** 想法3
   来自林晓勇的建议，或许可以加入对于速度的过滤，譬如 (MA5 - MA20)/MA20 可以看作是行情往上走的
   一种速度，对这种速度加上一个合适的阈值，是否就能对我们的交易信号进行比较好的过滤呢？

   同时比较 =ROC= 与新定义的变量，目的都是为了用一个速率的定义来表示趋势的强弱，但是，实际看起来
   =ROC= 表示的速率比新定义的变量表现的更明显，此外，由于新定义的变量是5、20均线系统定义出来的
   量，反应会比 =ROC= 慢，而 =ROC= 一个推荐的时间范围设置是12，与 =PSY= 默认定义的时间范围设置
   一致，是否 =ROC= 是更为合适的速率表示呢？

   但是， =ROC= 的过滤加入效果并不如人意，原本的想法是用 =ROC= 作为趋势确认的，不过，没啥用啊。
** 想法4
   仔细观察品种上应用 =PSY= 策略，同时审视了 =PSY= 的数学定义的意义，是否可以将最近几根 Bar柱
   的权重相当的加强，类似做指数均线一样的做法？
