#+TITLE: 指标总结
#+AUTHOR: 胡琛

* 威廉指标 (W&R)
  
** 原理

   分析周期内的最高价、最低价和周期结束时的收盘价三者之间的关系展开，以日威廉指标为例：

     \begin{equation}
       W&R = \frac{Highest(High, N) - Close}{Highest(High) - Lowest(Low)}\times 100
     \end{equation}

     原理上讲，威廉指标从研究股价波幅出发，通过分析一段时间内股票走势的最高价、最低价和收盘价这三者的关系，来
     反映市场买卖气势的强弱，借以考察阶段性市场气氛，判断价格与理性投资价值标准相背离的程度。

** 关于周期的说明

   计算时要决定周期天数，用此数取一个买卖循环的半数。许多分析专家认为一个买卖循环为28天，除开周六日，实际交易
   日为20天；一个较长的买卖循环为56天，除开周六日，交易日是40天；如果各取一半则为 10天和 20 天。此外，也有
   用 5 天周期来计算 WR 的，所以我们可以分别取 5， 10， 20 日不同基期长度做测试。

** 应用法则

   1. 当威廉指标高于 85 时，市场处于超卖状态，行情即将见底
   2. 当威廉指标低于15 时，市场处于超买状态，行情即将见顶
   3. 与相对强弱指标配合使用，可以得出对大盘走势较为准确的判断
   4. 使用威廉指标作为预测市场工具，既不容易错过大的行情，也不容易在高价区套牢

** 使用方法

   1. 当威廉指标高于80，即处于超卖状态，行情即将见底，应当考虑买进
   2. 当威廉指标低于20，即处于超买状态，行情即将见顶，应当考虑卖出
   3. 在威廉指标进入高位后，一般要回头，如果股价继续上升就产生了背离，是卖出信号
   4. 在威廉指标进入低位后，一般要反弹，如果股价继续下跌也产生了背离
   5. 在盘整阶段，威廉指标的准确性较高，而在上升或下降趋势中，却不能以WR作为超买超卖信号判断

** 参考文献与网址

   1. [[http://baike.baidu.com/item/%25E5%25A8%2581%25E5%25BB%2589%25E6%258C%2587%25E6%25A0%2587][威廉指标-百度百科]]
   2. [[https://www.joinquant.com/post/358884db1665713c3853d869ecb7fdff][优矿-威廉指标代码示例]]
   3. [[https://www.zhihu.com/question/35832910][知乎-威廉指标探讨]]

* KDJ指标

** 原理

   1. 未成熟随机值 (RSV)

      类似威廉指标的做法，不过计算公式稍作变形而已

       \begin{equation}
        RSV = \frac{Close - Lowest(High, N)}{Highest(High) - Lowest(Low)}\times 100
      \end{equation}

   2. K值计算

      =RSV= 的M 日平均

      \begin{equation}
        K = Average(RSV, M)
      \end{equation}

   3. D 值计算

     K 值的 L 日平均 

      \begin{equation}
        D = Average(D, M)
      \end{equation}

     
** 关于周期的选择

   网络流行的一种选择方式是 $N=9, M = 3, L =3$, 通达信上也是采用这种参数组合，TradeBlaze 则
   采用的是 $N=14, M = 3, L =3$ 这样的参数组合。

** 应用要则

   一般做大资金大波段的人来说，一般当月KDJ值在低位时逐步进场吸纳；主力平时运作时偏重周KDJ所处位置，
   对中波段的循环高低点做出研判结果，所以往往出现单边式日KDJ屡屡钝化现象；日KDJ对股价变化方向极为
   敏感，是日常买卖进出的重要方法；对于做小波段的短线客来说，30分钟和60分钟KDJ又是重要的参考指标；
   对于已指定买卖计划即刻下单的投资者，5分钟和15分钟KDJ可以提供最佳的进出时间。

** 应用方法
   
*** KD 判断方法
    1. K值与D值永远介于0到100之间。D大于80时，行情呈超买现象；D小于20时，行情呈超卖现象
    2. 上涨趋势中，K值大于D值，K线向上突破D线时，为买进信号；下跌趋势中，K值小于D值，K线向下跌破D线
       时，为卖出信号
    3. KD指标不仅能反应出市场的超买超卖程度，还能通过交叉突破发出买卖信号
    4. KD不适于发行量小，交易不活跃的股票，但是KD指标对于大盘和热门大盘股有极高准确性
    5. 当随机指标与股价出现背离时，一般为转势的信号
    6. K值与D值上升或者下跌的速度减弱，倾斜度趋于平缓时是短期转势的预警信号

*** J值判断方法
    1. J 大于 80，进入超买区，一般表示向上趋势延续
    2. J小于20，进入超卖区，一般表示还会继续下跌
    3. KDJ在短期趋势运行的过程中，J值超买超卖区，表示趋势继续延续；在20-80间利用位置关系，背离关系，顺势加仓或抓回撤（在20-80间的数值要一视同仁，50这个数没什么太大意义）。在短期震荡市中，J值超买超卖，表明可抓反手；在20-80间，同样利用位置关系，背离关系做加仓，抓回撤动作。所以一定要理解指标的含义，看当前短期内的K线走势，而不是见到超买超卖就反手，不能教条。
       
** 指标分析

   1. KD指标的背离。在KD处于高位或低位时，如果出现与股价走向的背离，则是采取行动的信号
   2. J取值超过100或低于0，都属于价格的非正常区域，大于100为超买，小于0为超卖
   3. KD的取值，KD的统一取值范围是0到100，我们可以将其划分为3个区域，80以上为超买区，
      20 以下为超卖区，其余为徘徊区，但这仅仅是一种信号提示，不能完全按照这种分析的方法进行
      操作
   4. KD指标的交叉，如果股价与MA的关系一样，也有死亡交叉和黄金交叉的问题
   5. KD指标曲线的形态，当KD指标在较高或较低的位置形成了头肩形和多重顶(底)时，是采取行动
      的信号。

** 实战应用
   1. 参数的选择
      KDJ常用参数是9，短线可以设置为5，常用的KDJ参数有5，9，19，36，45，73等，如果出现不同周期共振现象，
      说明趋势的可靠度加大。
   2. 研判
      - K线是快速确认线 -- 数值在90以上为超买，数值在10以下为超卖
      - D 线是慢速主干线 -- 数值在80以上为超卖，数值在20以下为超卖
      - J线是方向敏感线，当J值大于90，特别是连续5天以上时，股价至少会形成短期头部，反之，J小于10的时候，特别
        是连续数天以上，股价至少会形成短期底部
      - 当 KD 在 20 以下金叉的时候，此时短期买入信号较为准确；如果K值在50以下，由下往上两次上穿D值，形成右底
        比左底高的 “W底”形态时，后市股价可能会有相当的涨幅。
      - KD死叉为卖出信号，特别是在80以上死叉，卖出信号比较准确
      - 通过KDJ与股价背离的走势，判断股价顶底也是颇为实用的方法：A）股价创新高，KD没有创新高，为顶背离 B）股价
        创新低，而KD没有创新低，为底背离，应买入。
      
** 参考文献与网址

   1. [[https://www.zhihu.com/question/27652388/answer/37491605][何子垠-如何正确理解KDJ]]
   2. [[http://baike.baidu.com/item/KDJ%25E6%258C%2587%25E6%25A0%2587/6328421][百度百科-KDJ指标]]

* 思考
** 背离

   股价创新高，指标却出现往下走的情况，为何？

   以KDJ为例，J往下走 --> K,D差距变小 --> 短期RSV相比长期RSV变得更小 -- > 动量小 --> 趋势要反转
   KD差距变小，内在原因 --> RSV中收盘价的变化变小


   
   
